import "./globalStyles/normalize.css";
import "./globalStyles/globals.scss";
// import "bootstrap/dist/css/bootstrap.css"

export const metadata = {
  title: "Umnoj",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
