import "./globalStyles/normalize.css";
import "./globalStyles/globals.scss";
// import "bootstrap/dist/css/bootstrap.css"
import { useDispatch, useSelector } from "react-redux";
// import { decrement, increment } from "@/redux/counterReducer";



export const metadata = {
  title: "Umnoj",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>{children}</body>
    </html>
  );
}